<a href="https://colab.research.google.com/github/BanTai01/Data_Science/blob/main/2_Numpy_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy array Iteration

In [1]:
import numpy as np

In [2]:
my_np_array = np.array(
    [1,2,3,4,5,6]
)
print(my_np_array)

[1 2 3 4 5 6]


In [3]:
"""Option 1: Iterate by value
"""
for val in my_np_array:
  print(val)

1
2
3
4
5
6


In [6]:
"""Option 2: Iterate by Index"""
for i in range(len(my_np_array)):
  print(my_np_array[i])

1
2
3
4
5
6


In [7]:
# Option 3: Iterate by value and index
for i, val in enumerate(my_np_array):
  print(f"index = {i} value = {val}")

index = 0 value = 1
index = 1 value = 2
index = 2 value = 3
index = 3 value = 4
index = 4 value = 5
index = 5 value = 6


# Numpy methods


In [12]:
# Reshape
"""Condition : multiplication of dimension values before and after reshaping must be same
Step 1: flattening ->1D
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
Step 2: Reshaping
[[[1,2,3,4,],[6,7,8,9,10],[11,12,13,14,15]]] ===1,
"""
my_2d_array = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
        [13,14,15]
    ]
)
print(my_2d_array.shape)
print(my_2d_array.reshape(3,5))
print(my_2d_array.reshape(1, 3, 5))

(5, 3)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [19]:
"""Reshaping with -1
size of my_np_array = 3*4*2*2 = 48
if we want to reshape this into : 2*2*x or x*2*2 or 2*x*2=============2,2,-1
"""
my_np_array = np.zeros(shape= (3,4,2,2))

my_np_array_reshaped = my_np_array.reshape(2,2,-1)
print(my_np_array_reshaped.shape)

(2, 2, 12)


In [20]:
"""Sort"""
probabilities = np.array(
    [0.3,0.1,0.4,0.2]
)
probabilities_sorted = np.sort(probabilities)
print(probabilities_sorted)

probabilities_reverse_sorted = np.sort(probabilities)[::-1]
print(probabilities_reverse_sorted)

[0.1 0.2 0.3 0.4]
[0.4 0.3 0.2 0.1]


In [22]:
""" Argmax, Argmin """

index_max = np.argmax(probabilities)
print(index_max)

index_min = np.argmin(probabilities)
print(index_min)

2
1


In [27]:
""" Split """

my_np_array = np.array(
    [1,5,1,1,5,7]
)

new_np_array = np.split(
    my_np_array,
    indices_or_sections = 3
)
print(new_np_array)
print(new_np_array[0])
print(new_np_array[2])

[array([1, 5]), array([1, 1]), array([5, 7])]
[1 5]
[5 7]


In [30]:
 """ Dot Product
 v1 = 3i + 2j
 v2 = 3i - 4j

 v1 * v2 = (3*3)+(2* -4) = 1

 """
my_np_array1 = np.array(
    [1,2,3,4]
)
my_np_array2 = np.array(
    [5,6,7,8]
)
print(my_np_array1)
print(my_np_array2)

dot_product = np.dot(my_np_array1, my_np_array2)
print(dot_product)

[1 2 3 4]
[5 6 7 8]
70


In [32]:
"""Matrix Transpose"""
my_2d_array_1 = np.array(
    [
        [2,1,3],[7,5,6]
    ]
)
print(my_np_array1.shape)
print(my_2d_array_1.T)
print(my_np_array1.shape)

(4,)
[[2 7]
 [1 5]
 [3 6]]
(4,)


In [33]:
""" Mean, Median, Standard deviation
std = sqrt((x2-mean)^2 + (x2-mean)^2......../(n-1))
"""

my_np_array = np.array(
    [1,5,1,1,5,7]
)

print(np.mean(my_np_array))
print(np.median(my_np_array))
print(np.std(my_np_array))

3.3333333333333335
3.0
2.4267032964268394


# Numpy Filtering


In [34]:
""" Numpy filter
Option 1: Boolean mask
Option 2: Conditional
Option 3: Indices
"""
my_np_array0 = np.array(
    [1,2,3,4,5,6]
)

filter_mask = [True, False, True, False, True, False]
filtered_array = my_np_array0[filter_mask]
print(filtered_array)

[1 3 5]


In [36]:
filter_mask = (my_np_array0 % 2 == 1)
print(filter_mask)
filtered_array = my_np_array0[filter_mask]
print(filtered_array)

[ True False  True False  True False]
[1 3 5]


In [37]:
indices = [0, 2, 5]
filtered_array = my_np_array0[indices]
print(filtered_array)

[1 3 6]


In [38]:
""" Custom filter method"""
def my_filter_method(x):
  if x % 2 == 0:
    return False
  return True

filtered_iterable = filter(my_filter_method, my_np_array0)
my_filtered_array = np.array(
    list(filtered_iterable)
)

my_filtered_array

array([1, 3, 5])

# Vectorization


In [41]:
my_1d_array = np.array(
    [1,2,3,4,5]
)
print(my_1d_array)
my_1d_array % 2 == 1


my_1d_array = my_1d_array + 5
print(my_1d_array)

[1 2 3 4 5]
[ 6  7  8  9 10]


# Broadcasting


In [42]:
""" Broadcasting
- converting a lower shape into higher shape for vectorization
"""
w = np.array(
    [1,2]
)
x = np.array(
    [
        [3,4],
        [5,6],
        [7, -8],
        [-5, -3]
    ]
)
print(w*x)

[[  3   8]
 [  5  12]
 [  7 -16]
 [ -5  -6]]
