<a href="https://colab.research.google.com/github/BanTai01/Data_Science/blob/main/3_Numpy_axis_and_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
my_np_array = np.zeros(
    shape = (2, 3, 2)
)
print(my_np_array.ndim)
print(my_np_array)

3
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [10]:
"""
First dimension: axis = 0
second dimension: axis = 1
Third dimension: axis = 2
....
N th dimension: axis = N - 1

aggregation function: sum, min, max, median
"""

my_2d_array = np.array(
    [
        [1, 5, -2],
        [0, 1, 9]
    ]
)
print(my_2d_array.shape)
print(f"Sum is {np.sum(my_2d_array, axis = 1 )}")

print(f"Sum is {np.sum(my_2d_array, axis = 0 )}")


(2, 3)
Sum is [ 4 10]
Sum is [1 6 7]


In [12]:
my_3d_array = np.zeros(
    shape = (3, 2, 2)
)
print(my_3d_array)
print(np.sum(my_3d_array, axis=0).shape)
print(np.sum(my_3d_array, axis=1).shape)
print(np.sum(my_3d_array, axis=2).shape)


[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2)
(3, 2)
(3, 2)


# Numpy Random



In [16]:
print(np.random.rand(5))
print(type(np.random.rand(5)))

[0.69033555 0.81115878 0.82188069 0.68045741 0.32844063]
<class 'numpy.ndarray'>


In [22]:
random_array = np.random.randint(100, size=(2,5))
print(random_array)


[[86 34 42  2 37]
 [28 99  5 11 39]]


In [27]:
np.random.shuffle(random_array)
print(random_array)

[[86 34 42  2 37]
 [28 99  5 11 39]]


In [32]:
""" Datasets are divided into three types:
1: training datasets
2: validation datasets
3: test datasets
"""
datasets = np.random.rand(1000, 5)
print("Datasets :\n", datasets[:5])


Datasets :
 [[0.17760992 0.18659466 0.09626059 0.63323974 0.00739694]
 [0.34305853 0.64705006 0.56668777 0.40455671 0.42339537]
 [0.17959448 0.72996479 0.21348118 0.27175042 0.81589693]
 [0.63490535 0.81548592 0.03100211 0.83807336 0.19147215]
 [0.24593425 0.24122293 0.34775187 0.77901798 0.98130507]]


In [33]:
np.random.shuffle(datasets)
print(datasets[:5])

[[0.44133293 0.65909678 0.58950493 0.56085952 0.59400338]
 [0.09300517 0.10751414 0.71791061 0.10906975 0.9061152 ]
 [0.59628241 0.81016475 0.21017232 0.30906555 0.32312803]
 [0.26072751 0.41554576 0.95328016 0.66143054 0.10035385]
 [0.91562378 0.41042525 0.30172214 0.80756809 0.34618545]]


In [34]:
""" step 2: split"""

index_1 = int(0.8 * len(datasets))
index_2 = int(0.9 * len(datasets))
trainset, valset, testset = np.split(
    datasets, [index_1, index_2],
)
print(len(trainset), len(valset), len(testset))

800 100 100
