<a href="https://colab.research.google.com/github/BanTai01/Data_Science/blob/main/Numpy_Basic_1st_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.__version__

'1.26.4'

In [ ]:
# create a numpy array
"""
numpy properties: dtype, shape, ndim, type
print(type(my_np_array))
"""

my_np_array = np.array(
    [1,2,3,4,5]
)
print(my_np_array)
print(type(my_np_array))
print(my_np_array.dtype)
print(my_np_array.shape)
print(my_np_array.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
1


In [8]:
"""
Create an array with all zeros
"""
zeros_np_array = np.zeros(
    shape = (5,)
)
zeros_np_array

array([0., 0., 0., 0., 0.])

In [9]:
"""
Create Identity Matrix
"""
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
""" Type Cast
Conversion of data type
"""
my_empty_np_array = np.empty(
    shape = (5,)
)
print(my_empty_np_array)
print(my_empty_np_array.dtype)

[0. 0. 0. 0. 0.]
float64


In [22]:
"""Create a sequential array
"""
my_array = np.arange(start=1, stop=10, step=2)
my_array

array([1, 3, 5, 7, 9])

In [23]:
my_array = np.arange(1, 10, 1)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
"""
Start, A, B, C, Stop
---all are same distance---
"""
my_np_array = np.linspace(
    start = 0,
    stop = 10,
    num = 5
)
my_np_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
"""
Numpy array Dimensions
-scalar -> 0D
-vector -> 1D
-matrix -> 2D
-tensor -> xD where x>2
tensor is a unit data type of pyTorch and TensorFlow
"""
my_empty_np_array = np.empty(
    shape = (5, 3, 7)
)
print(my_empty_np_array)
print(my_empty_np_array.dtype)


[[[4.95356771e-310 0.00000000e+000 3.83889007e-321             nan
   1.12646967e-321 0.00000000e+000 1.54417150e+256]
  [5.38970828e+228 1.87673447e-152 6.96742168e+252 5.81241635e+180
   6.01334434e-154 5.81948471e+199 9.75394660e+199]
  [2.32159323e-152 9.75384927e+199 3.99255546e+252 1.09857249e-152
   4.44032500e+252 4.08841057e+233 6.01346954e-154]]

 [[7.22928306e+159 6.96769793e+252 1.39806874e-152 1.49457388e+195
   9.30537467e+199 2.03481699e+174 2.43861180e-152]
  [7.22939910e+159 1.52394763e-258 6.01347002e-154 3.17095864e+180
   5.26750370e+170 7.69110575e+218 1.23557999e-259]
  [6.01347002e-154 2.55796528e-152 7.35989720e+223 7.26607058e+223
   3.99255546e+252 1.09857249e-152 1.21906490e-152]]

 [[1.82822904e+044 2.21494665e+068 1.78436354e-258 6.01347002e-154
   1.81270012e-152 7.67112743e+170 4.78714289e+180]
  [1.42499357e+248 2.13663437e+161 9.30860811e+199 8.70860497e+183
   1.69376034e+190 6.01346953e-154 6.01347002e-154]
  [1.96631951e-153 2.25538746e+276 8.8767085

In [27]:
"""Numpy indexing
1. Non-negetive Indexing (0, 1, 2, ......)
2. Negetive Indexing (-1, -2, ..........)
"""
my_np_array = np.array(
    [1,2,3,4,5,6,7,8]
)
print(my_np_array[2])
print(my_np_array[-6])

3
3


In [32]:
my_2d_array = np.array(
    [[1,2,3,4],
     [5,6,7,8],
    [7,8,9,10]]
)
print(my_2d_array[1,1])
print(my_2d_array[-2,-3])

6
6


In [35]:
"""
numpy slicing
"""
my_1d_array = np.array(
    [1,2,3,4,5,6,7]
)
print(my_1d_array[1:4:1])
print(my_1d_array[0:8:2])

[2 3 4]
[1 3 5 7]


In [36]:
my_1d_array = np.array(
    [1,2,3,4,5,6,7]
)
print(my_1d_array[::])
print(my_1d_array[2:5])
print(my_1d_array[1:5:2])

[1 2 3 4 5 6 7]
[3 4 5]
[2 4]


In [39]:
my_2d_array = np.array(
    [[1,2,3,4],
     [5,6,7,8],
    [7,8,9,10]]
)
print(my_2d_array[0:2,1:3])

[[2 3]
 [6 7]
 [8 9]]
