<a href="https://colab.research.google.com/github/BanTai01/Data_Science/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importing Libraries**

In [1]:
import numpy as np

In [9]:
my_np_array = np.array(
    [1,2,3,4,6,7,8]
)
print(my_np_array)
print(type(my_np_array))
print(my_np_array.dtype)
print(my_np_array.shape)
print(my_np_array.ndim)

[1 2 3 4 6 7 8]
<class 'numpy.ndarray'>
(7,)
1


# Create and array with all zeros

In [16]:
zeros_np_array = np.zeros(
    shape = (5,)
)
print(zeros_np_array)

ones_np_array = np.ones(
    shape = (3,3),
    dtype = 'int'
)
print(ones_np_array)

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
specific_np_array = np.full(
    shape = (4,3),
    fill_value = 15,
)
print(specific_np_array)

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [21]:
# creating identity matrix
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
random_np_array = np.empty(
    shape = (5,)
)
print(random_np_array)

[0. 0. 0. 0. 0.]


# Type casting


In [32]:
print(random_np_array.dtype)
random_np_array = random_np_array.astype('int')
print(random_np_array)
print(random_np_array.dtype)


int64
[0 0 0 0 0]
int64


# Creating sequential array

In [33]:
my_array = np.arange(start = 1, stop = 10, step = 1)
print(my_array)

[1 2 3 4 5 6 7 8 9]


In [34]:
my_np_arrays = np.linspace(
    start = 0,
    stop = 10,
    num = 5,
)
print(my_np_arrays)

[ 0.   2.5  5.   7.5 10. ]


# Multi dimensional array

In [35]:
"""numpy array dimensions
mathematical objects
-scalar = 0D
-vector = 1D
-Matrix = 2D
-Tensor = xD where x>2

Tensor is a unit data
"""
specific_np_array = np.full(
    shape = (4,3, 5),
    fill_value = 15,
)
print(specific_np_array)


[[[15 15 15 15 15]
  [15 15 15 15 15]
  [15 15 15 15 15]]

 [[15 15 15 15 15]
  [15 15 15 15 15]
  [15 15 15 15 15]]

 [[15 15 15 15 15]
  [15 15 15 15 15]
  [15 15 15 15 15]]

 [[15 15 15 15 15]
  [15 15 15 15 15]
  [15 15 15 15 15]]]


# Numpy Array Indexing

In [36]:
my_np_array = np.array(
    [1,2,3,4,5,6,7,8,9]
)
print(my_np_array[3])
print(my_np_array[-6])

4
4


In [41]:
my_2d_array = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
print(my_2d_array[1,1])
print(my_2d_array[1,-3])

6
6


In [45]:
my_3d_array = np.array([
    [[1,2,3,4],[2,3,4,5]],
    [[4,5,6,7],[6,5,4,3]]
])
print(my_3d_array[1,1,-1]) #index(1d, 2d, 3d)

3


# Slicing numpy array


In [50]:
my_np_array = np.array(
    [1,2,3,4,5,6,7,8,9]
)
print(my_np_array[0:8:2])
print(my_np_array[::])
print(my_np_array[2:5])

[1 3 5 7]
[1 2 3 4 5 6 7 8 9]
[3 4 5]


In [53]:
my_2d_array = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
)
print(my_2d_array[0:3, 1:3])
print(my_2d_array[0:3, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]
